[general]
case = "my_beautiful_case"
data_rootdir = "/scratch/nhs/deode/data"
outdir = "/scratch/nhs/deode/"
os_macros = ["USER", "HOME", "PWD"]
domain = "FUNEN"
basetime = "2020-08-15T03:00:00+00:00"
validtime = "2020-08-15T04:00:00+00:00"
realization = -1
cnmexp = "DEOD"
tstep = 60
loglevel = "DEBUG"

[general.times]
basetime = "2020-08-15T03:00:00+00:00"
validtime = "2020-08-15T04:00:00+00:00"
start = "2020-08-15T00:00:00+00:00"
end = "2020-08-16T21:00:00+00:00"
cycle_length = "PT3H"

[system]
wrk = "/@SCRATCH@/"

[platform]
bindir = "/tmp/bindir"
archive = "/tmp/archive/@YYYY@/@MM@/@DD@/@HH@"
scratch = "/scratch/@USER@/deode/"
climdata = "/ec/res4/hpcperm/hlam/data/climate"
soilgrid_data_path = "@CLIMDATA@/SOILGRID"
gmted2010_data_path = "@CLIMDATA@/GMTED2010"
deode_home = "@PWD@"

[domain]
name   = "FUNEN"
nlon   = 50
nlat   = 50
tstep  = 60
levels = 65
lonc   = 10.2
latc   = 55.2
lon0   = 10.0
lat0   = 56.7
gsize  = 2500.0

[submission]
submit_types = ["background_vm", "background_hpc", "serial", "parallel"]
default_submit_type = "serial"
[submission.background_vm]
INTERPRETER = "#!/usr/bin/python3"
SCHOST = "localhost"
tasks = ["Background_vm"]

[submission.background_hpc]
SCHOST = "localhost"
tasks = ["Background_hpc"]

[submission.serial]
SCHOST = "hpc"
[submission.serial.BATCH]
ACCOUNT = "#SBATCH -A msdeode"
WALLTIME = "#SBATCH --time=00:05:00"

[submission.parallel]
SCHOST = "hpc"
tasks = ["Soil"]
[submission.parallel.BATCH]
ACCOUNT = "#SBATCH -A msdeode"
WALLTIME = "#SBATCH --time=00:10:00"

[troika]
config_file = "@DEODE_HOME@/deode/data/config_files/troika.yml"
